/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace InventoryTracker {
  export type MovementStruct = {
    itemId: string;
    fromLocation: string;
    toLocation: string;
    quantity: BigNumberish;
    movementType: string;
    handler: AddressLike;
    timestamp: BigNumberish;
    ipfsHash: string;
  };

  export type MovementStructOutput = [
    itemId: string,
    fromLocation: string,
    toLocation: string,
    quantity: bigint,
    movementType: string,
    handler: string,
    timestamp: bigint,
    ipfsHash: string
  ] & {
    itemId: string;
    fromLocation: string;
    toLocation: string;
    quantity: bigint;
    movementType: string;
    handler: string;
    timestamp: bigint;
    ipfsHash: string;
  };
}

export interface InventoryTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedHandlers"
      | "getLatestLocation"
      | "getMovementHistory"
      | "recordMovement"
      | "verifyIntegrity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AlertRaised" | "InventoryMoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedHandlers",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestLocation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMovementHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordMovement",
    values: [string, string, string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIntegrity",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedHandlers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMovementHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordMovement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIntegrity",
    data: BytesLike
  ): Result;
}

export namespace AlertRaisedEvent {
  export type InputTuple = [
    itemId: string,
    alertType: string,
    description: string
  ];
  export type OutputTuple = [
    itemId: string,
    alertType: string,
    description: string
  ];
  export interface OutputObject {
    itemId: string;
    alertType: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InventoryMovedEvent {
  export type InputTuple = [
    itemId: string,
    fromLocation: string,
    toLocation: string,
    quantity: BigNumberish,
    movementType: string,
    handler: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    itemId: string,
    fromLocation: string,
    toLocation: string,
    quantity: bigint,
    movementType: string,
    handler: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    itemId: string;
    fromLocation: string;
    toLocation: string;
    quantity: bigint;
    movementType: string;
    handler: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InventoryTracker extends BaseContract {
  connect(runner?: ContractRunner | null): InventoryTracker;
  waitForDeployment(): Promise<this>;

  interface: InventoryTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedHandlers: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getLatestLocation: TypedContractMethod<[_itemId: string], [string], "view">;

  getMovementHistory: TypedContractMethod<
    [_itemId: string],
    [InventoryTracker.MovementStructOutput[]],
    "view"
  >;

  recordMovement: TypedContractMethod<
    [
      _itemId: string,
      _fromLocation: string,
      _toLocation: string,
      _quantity: BigNumberish,
      _movementType: string,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;

  verifyIntegrity: TypedContractMethod<
    [_itemId: string, _expectedHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedHandlers"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLatestLocation"
  ): TypedContractMethod<[_itemId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getMovementHistory"
  ): TypedContractMethod<
    [_itemId: string],
    [InventoryTracker.MovementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordMovement"
  ): TypedContractMethod<
    [
      _itemId: string,
      _fromLocation: string,
      _toLocation: string,
      _quantity: BigNumberish,
      _movementType: string,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyIntegrity"
  ): TypedContractMethod<
    [_itemId: string, _expectedHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AlertRaised"
  ): TypedContractEvent<
    AlertRaisedEvent.InputTuple,
    AlertRaisedEvent.OutputTuple,
    AlertRaisedEvent.OutputObject
  >;
  getEvent(
    key: "InventoryMoved"
  ): TypedContractEvent<
    InventoryMovedEvent.InputTuple,
    InventoryMovedEvent.OutputTuple,
    InventoryMovedEvent.OutputObject
  >;

  filters: {
    "AlertRaised(string,string,string)": TypedContractEvent<
      AlertRaisedEvent.InputTuple,
      AlertRaisedEvent.OutputTuple,
      AlertRaisedEvent.OutputObject
    >;
    AlertRaised: TypedContractEvent<
      AlertRaisedEvent.InputTuple,
      AlertRaisedEvent.OutputTuple,
      AlertRaisedEvent.OutputObject
    >;

    "InventoryMoved(string,string,string,uint256,string,address,uint256)": TypedContractEvent<
      InventoryMovedEvent.InputTuple,
      InventoryMovedEvent.OutputTuple,
      InventoryMovedEvent.OutputObject
    >;
    InventoryMoved: TypedContractEvent<
      InventoryMovedEvent.InputTuple,
      InventoryMovedEvent.OutputTuple,
      InventoryMovedEvent.OutputObject
    >;
  };
}
